name: build the python program

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:  #It is used to share and reuse the workflows across the project or repos. 
  # workflow_dispatch: # when you want to manually trigger a workflow from the UI
  schedule: 
    - cron: '55 7 * * 6'
  

jobs:
  build: 
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - name: checkout this yml to main branch
        uses: actions/checkout@v4

      - name: python setup in the github server
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Run python script
        run: python helloworld.py

      - name: using list yml file
        run: kishorekumarsajja/my_project_1/blank.yml@V1.0
      
